<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Successfull Registration</title>
</head>

<body>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td align="center" valign="top" bgcolor="#ebeced"
        style="background-color:#ffffff;"><br> <br>
<img src="https://thumbs2.imgbox.com/10/a6/0DKaDCx2_t.png" alt="image host"
        bgcolor="#ebeced"
        style="background-color: #ebeced;"/>
<table width="600" border="0"
        cellspacing="0" cellpadding="0">
<tr>
<td  align="center" valign="top" bgcolor="#d3be6c"
        style="background-color: #f5f6f7; font-family: Arial,
        Helvetica, sans-serif; font-size: 13px; color: #000000;
        padding: 0px 15px 30px 15px;">

<div style="font-size: 35px; color: #0a0a0a;">
<br><b>Just one more step...</b> <br>
</div>
<div style="font-size: 16px; color: #0a0a0a; font-weight:bold;">
<b><br>${user}</b><br>
</div>
<div>
<br><br>Click the big button below to active your MailChimp account.<br> <br><span>
<br><a href="http://localhost:8080/confirm-account?token=${token}"
        style="font: bold 15px Arial; text-decoration: none; background-color: #45bfbf;
        color: #f7fcfc;
        padding: 10px 10px 10px 10px;">
        Activate Account</a>
</span>
<br>
</div>
</td>
</tr>
</table> <br>
<p style="color:#4d4545; font-size:11px; line-height:13px; font-family:arial; font-weight:bold;">
@ 2013 MailChimps, All Rights Reserved.<br>
            512 Means St. * Suite 404 * Atlanta, GA 30318 USA
</p><br>
<img src="https://thumbs2.imgbox.com/d7/94/UvnrWuKO_t.png" alt="image host"
        bgcolor="#ffffff"
        style="background-color: #ffffff;"/>
</td>
</tr>
</table>
</body>
</html>